const mockProducts = [
  {
    category_id: 1,
    category_name: 'Fashion',
    product_id: 1,
    product_name: 'Fashion Product 1',
    price: 50.99,
    currency: 'USD',
    image: 'fashion1.jpg',
    short_description: 'Description for Fashion Product 1',
    rating: 4.5,
  },
  {
    category_id: 1,
    category_name: 'Fashion',
    product_id: 2,
    product_name: 'Fashion Product 2',
    price: 79.99,
    currency: 'USD',
    image: 'fashion2.jpg',
    short_description: 'Description for Fashion Product 2',
    rating: 3.8,
  },
  {
    category_id: 2,
    category_name: 'Shoes',
    product_id: 3,
    product_name: 'Shoes Product 1',
    price: 120.5,
    currency: 'USD',
    image: 'shoes1.jpg',
    short_description: 'Description for Shoes Product 1',
    rating: 4.2,
  },
  {
    category_id: 2,
    category_name: 'Shoes',
    product_id: 4,
    product_name: 'Shoes Product 2',
    price: 89.99,
    currency: 'USD',
    image: 'shoes2.jpg',
    short_description: 'Description for Shoes Product 2',
    rating: 4.0,
  },
  {
    category_id: 3,
    category_name: 'Shirts',
    product_id: 5,
    product_name: 'Shirts Product 1',
    price: 35.5,
    currency: 'USD',
    image: 'shirts1.jpg',
    short_description: 'Description for Shirts Product 1',
    rating: 4.7,
  },
  {
    category_id: 3,
    category_name: 'Shirts',
    product_id: 6,
    product_name: 'Shirts Product 2',
    price: 45.99,
    currency: 'USD',
    image: 'shirts2.jpg',
    short_description: 'Description for Shirts Product 2',
    rating: 4.1,
  },
  {
    category_id: 4,
    category_name: 'Books',
    product_id: 7,
    product_name: 'Book 1',
    price: 20.99,
    currency: 'USD',
    image: 'book1.jpg',
    short_description: 'Description for Book 1',
    rating: 4.8,
  },
  {
    category_id: 4,
    category_name: 'Books',
    product_id: 8,
    product_name: 'Book 2',
    price: 15.5,
    currency: 'USD',
    image: 'book2.jpg',
    short_description: 'Description for Book 2',
    rating: 4.3,
  },
];

const mockresult = [
  {
    category: 'Fashion',
    products: [
      {
        id: '0.0059728021305916245',
        product_name: 'Adidas Ultraboost',
        price: '156.25',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?phones',
        short_description: 'Compact and easy to fly',
        rating: {
          rating: 1,
          count: 34,
        },
      },
      {
        id: '0.003470276540727039',
        product_name: 'Sony PlayStation 5',
        price: '635.88',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?gaming-console',
        short_description: 'Portable gaming console',
        rating: {
          rating: 2,
          count: 31,
        },
      },
      {
        id: '0.004161012645819506',
        product_name: 'Bose Noise-Cancelling Headphones',
        price: '825.50',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?drone',
        short_description: 'Compact and easy to fly',
        rating: {
          rating: 1,
          count: 58,
        },
      },
      {
        id: '0.004409377349761859',
        product_name: 'Nike SB Dunk',
        price: '510.63',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?electronics',
        short_description: 'Limited stock available',
        rating: {
          rating: 1,
          count: 11,
        },
      },
      {
        id: '0.0075657152458812275',
        product_name: 'Nike SB Dunk',
        price: '161.91',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?gaming',
        short_description: 'Immersive gaming experience',
        rating: {
          rating: 2,
          count: 43,
        },
      },
    ],
  },
  {
    category: 'Shirts',
    products: [
      {
        id: '0.0059728021305916245',
        product_name: 'Adidas Ultraboost',
        price: '156.25',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?phones',
        short_description: 'Compact and easy to fly',
        rating: {
          rating: 1,
          count: 34,
        },
      },
      {
        id: '0.003470276540727039',
        product_name: 'Sony PlayStation 5',
        price: '635.88',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?gaming-console',
        short_description: 'Portable gaming console',
        rating: {
          rating: 2,
          count: 31,
        },
      },
      {
        id: '0.004161012645819506',
        product_name: 'Bose Noise-Cancelling Headphones',
        price: '825.50',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?drone',
        short_description: 'Compact and easy to fly',
        rating: {
          rating: 1,
          count: 58,
        },
      },
      {
        id: '0.004409377349761859',
        product_name: 'Nike SB Dunk',
        price: '510.63',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?electronics',
        short_description: 'Limited stock available',
        rating: {
          rating: 1,
          count: 11,
        },
      },
      {
        id: '0.0075657152458812275',
        product_name: 'Nike SB Dunk',
        price: '161.91',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?gaming',
        short_description: 'Immersive gaming experience',
        rating: {
          rating: 2,
          count: 43,
        },
      },
    ],
  },
  {
    category: 'Shoes',
    products: [
      {
        id: '0.0059728021305916245',
        product_name: 'Adidas Ultraboost',
        price: '156.25',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?phones',
        short_description: 'Compact and easy to fly',
        rating: {
          rating: 1,
          count: 34,
        },
      },
      {
        id: '0.003470276540727039',
        product_name: 'Sony PlayStation 5',
        price: '635.88',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?gaming-console',
        short_description: 'Portable gaming console',
        rating: {
          rating: 2,
          count: 31,
        },
      },
      {
        id: '0.004161012645819506',
        product_name: 'Bose Noise-Cancelling Headphones',
        price: '825.50',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?drone',
        short_description: 'Compact and easy to fly',
        rating: {
          rating: 1,
          count: 58,
        },
      },
      {
        id: '0.004409377349761859',
        product_name: 'Nike SB Dunk',
        price: '510.63',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?electronics',
        short_description: 'Limited stock available',
        rating: {
          rating: 1,
          count: 11,
        },
      },
      {
        id: '0.0075657152458812275',
        product_name: 'Nike SB Dunk',
        price: '161.91',
        currency: '₦',
        image: 'https://source.unsplash.com/600x400/?gaming',
        short_description: 'Immersive gaming experience',
        rating: {
          rating: 2,
          count: 43,
        },
      },
    ],
  },
];

export { mockProducts, mockresult };
